//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMAMUS.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIMAMUSEntities : DbContext
    {
        public SIMAMUSEntities()
            : base("name=SIMAMUSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CentroSalud> CentroSalud { get; set; }
        public virtual DbSet<Especialidad> Especialidad { get; set; }
        public virtual DbSet<Medico> Medico { get; set; }
        public virtual DbSet<NivelUsuario> NivelUsuario { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Radiologo> Radiologo { get; set; }
        public virtual DbSet<RegionEstudio> RegionEstudio { get; set; }
        public virtual DbSet<RegistroResultados> RegistroResultados { get; set; }
        public virtual DbSet<Sector> Sector { get; set; }
        public virtual DbSet<Sexo> Sexo { get; set; }
        public virtual DbSet<TipoConsulta> TipoConsulta { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
