//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMAMUS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroResultados
    {
        public int IdRegistro { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaEstudio { get; set; }
        public string Hallazgos { get; set; }
        public string Conclusiones { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public Nullable<int> IdMedico { get; set; }
        public Nullable<int> IdRadiologo { get; set; }
        public Nullable<int> IdRegion { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdTipoConsulta { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual Radiologo Radiologo { get; set; }
        public virtual RegionEstudio RegionEstudio { get; set; }
        public virtual TipoConsulta TipoConsulta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
