//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMAMUS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroResultados
    {
        public int IdRegistro { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public System.DateTime fechaEstudio { get; set; }
        public string Hallazgos { get; set; }
        public string Conclusiones { get; set; }
        public int IdPaciente { get; set; }
        public int IdMedico { get; set; }
        public int IdRadiologo { get; set; }
        public int IdRegion { get; set; }
        public int IdUsuario { get; set; }
        public int IdTipoConsulta { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual Radiologo Radiologo { get; set; }
        public virtual RegionEstudio RegionEstudio { get; set; }
        public virtual TipoConsulta TipoConsulta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
