//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMAMUS.GUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroResultados
    {
        public int IdRegistro { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public System.DateTime fechaEstudio { get; set; }
        public string Hallazgos { get; set; }
        public string Conclusiones { get; set; }
        public int CedulaPaciente { get; set; }
        public int CodigoMedico { get; set; }
        public int CodigoRadiologo { get; set; }
        public int IdRegion { get; set; }
        public string NombreUsuario { get; set; }
        public int IdTipoConsulta { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Radiologo Radiologo { get; set; }
        public virtual RegionEstudio RegionEstudio { get; set; }
        public virtual TipoConsulta TipoConsulta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
