//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMAMUS.GUI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SIMAMUSEntities : DbContext
    {
        public SIMAMUSEntities()
            : base("name=SIMAMUSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CentroSalud> CentroSalud { get; set; }
        public virtual DbSet<Especialidad> Especialidad { get; set; }
        public virtual DbSet<Medico> Medico { get; set; }
        public virtual DbSet<NivelUsuario> NivelUsuario { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Radiologo> Radiologo { get; set; }
        public virtual DbSet<RegionEstudio> RegionEstudio { get; set; }
        public virtual DbSet<RegistroResultados> RegistroResultados { get; set; }
        public virtual DbSet<Sector> Sector { get; set; }
        public virtual DbSet<Sexo> Sexo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoConsulta> TipoConsulta { get; set; }
        public virtual DbSet<TipoExamen> TipoExamen { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<pro_Reportes_Result> pro_Reportes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_Reportes_Result>("pro_Reportes");
        }
    
        public virtual ObjectResult<pro_ReportesP_Result> pro_ReportesP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_ReportesP_Result>("pro_ReportesP");
        }
    
        public virtual ObjectResult<pro_ReportesParametros_Result> pro_ReportesParametros(Nullable<int> idR)
        {
            var idRParameter = idR.HasValue ?
                new ObjectParameter("IdR", idR) :
                new ObjectParameter("IdR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_ReportesParametros_Result>("pro_ReportesParametros", idRParameter);
        }
    }
}
